# https://taskfile.dev

version: '3'



tasks:
  MessageBusSample:
    desc: Message bus sample
    cmds:
      -  dotnet run --project Code/Sample/Test/ConsoleApp1/ConsoleApp1.csproj
    silent: true
